"""replace username with email

Revision ID: 123dd664252e
Revises: 4b15789a56a0
Create Date: 2024-11-15 21:51:59.189713

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '123dd664252e'
down_revision: Union[str, None] = '4b15789a56a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('planilhas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('data_venda', sa.Date(), nullable=False),
    sa.Column('data_pagamento', sa.Date(), nullable=False),
    sa.Column('valor_bruto', sa.Float(), nullable=False),
    sa.Column('valor_liquido', sa.Float(), nullable=False),
    sa.Column('taxa', sa.Float(), nullable=False),
    sa.Column('forma_pagamento', sa.String(), nullable=False),
    sa.Column('nome_produto', sa.String(), nullable=False),
    sa.Column('categoria_produto', sa.String(), nullable=False),
    sa.Column('historic_dashboard_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['historic_dashboard_id'], ['historic_dashboard.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('panilhas')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('panilhas',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('data_venda', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('data_pagamento', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('valor_bruto', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('valor_liquido', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('taxa', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('forma_pagamento', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('nome_produto', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('categoria_produto', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('historic_dashboard_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['historic_dashboard_id'], ['historic_dashboard.id'], name='panilhas_historic_dashboard_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='panilhas_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='panilhas_pkey')
    )
    op.drop_table('planilhas')
    # ### end Alembic commands ###
