"""replace username with email

Revision ID: 4b15789a56a0
Revises: f6e82e617c88
Create Date: 2024-11-15 21:50:14.461761

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b15789a56a0'
down_revision: Union[str, None] = 'f6e82e617c88'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('panilhas', sa.Column('historic_dashboard_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'panilhas', 'historic_dashboard', ['historic_dashboard_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'panilhas', type_='foreignkey')
    op.drop_column('panilhas', 'historic_dashboard_id')
    # ### end Alembic commands ###
