"""Add indexes on planilhas and historic_dashboard foreign keys and data_venda

Revision ID: 732ba8895414
Revises: a536749e4acc
Create Date: 2026-08-09 18:47:48.713677

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '732ba8895414'
down_revision: Union[str, None] = 'a536749e4acc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_historic_dashboard_user_id'), 'historic_dashboard', ['user_id'], unique=False)
    op.create_index(op.f('ix_planilhas_data_venda'), 'planilhas', ['data_venda'], unique=False)
    op.create_index(op.f('ix_planilhas_historic_dashboard_id'), 'planilhas', ['historic_dashboard_id'], unique=False)
    op.create_index(op.f('ix_planilhas_user_id'), 'planilhas', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_planilhas_user_id'), table_name='planilhas')
    op.drop_index(op.f('ix_planilhas_historic_dashboard_id'), table_name='planilhas')
    op.drop_index(op.f('ix_planilhas_data_venda'), table_name='planilhas')
    op.drop_index(op.f('ix_historic_dashboard_user_id'), table_name='historic_dashboard')
    # ### end Alembic commands ###
