"""replace username with email

Revision ID: 9b73a0d3f688
Revises: c87e2449b2ef
Create Date: 2024-10-12 23:03:52.617113

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b73a0d3f688'
down_revision: Union[str, None] = 'c87e2449b2ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('panilhas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('data_venda', sa.Date(), nullable=False),
    sa.Column('data_pagamento', sa.Date(), nullable=False),
    sa.Column('valor_bruto', sa.Float(), nullable=False),
    sa.Column('valor_liquido', sa.Float(), nullable=False),
    sa.Column('taxa', sa.Float(), nullable=False),
    sa.Column('forma_pagamento', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('panilhas')
    # ### end Alembic commands ###
