"""Create users, planilhas and historic_dashboard tables

Revision ID: a536749e4acc
Revises: d84036e39d13
Create Date: 2026-08-09 18:40:29.046594

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a536749e4acc'
down_revision: Union[str, None] = 'd84036e39d13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('historic_dashboard',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('data_upload_planilha', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('planilhas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('data_venda', sa.Date(), nullable=False),
    sa.Column('data_pagamento', sa.Date(), nullable=False),
    sa.Column('valor_bruto', sa.Float(), nullable=False),
    sa.Column('valor_liquido', sa.Float(), nullable=False),
    sa.Column('taxa', sa.Float(), nullable=False),
    sa.Column('forma_pagamento', sa.String(), nullable=False),
    sa.Column('nome_produto', sa.String(), nullable=False),
    sa.Column('categoria_produto', sa.String(), nullable=False),
    sa.Column('historic_dashboard_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['historic_dashboard_id'], ['historic_dashboard.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('planilhas')
    op.drop_table('historic_dashboard')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
